"""PDF export — generate printable reports as styled HTML."""
from datetime import datetime
from . import db, stats as stats_mod


_CSS = """
body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; color: #111; }
h1 { border-bottom: 2px solid #111; padding-bottom: 10px; }
h2 { color: #333; margin-top: 30px; }
.stat { display: inline-block; padding: 10px 20px; background: #f5f5f5; margin: 5px; border-radius: 8px; }
.stat-value { font-size: 24px; font-weight: bold; display: block; }
.stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 8px; border-bottom: 1px solid #ddd; text-align: left; }
th { background: #f5f5f5; }
.footer { margin-top: 40px; font-size: 11px; color: #999; }
"""


def generate_report_text(conn) -> str:
    """Plain-text report."""
    score = stats_mod.calculate_score(conn)
    bd = stats_mod.get_daily_breakdown(conn)
    top = stats_mod.get_top_distractions(conn, days=7)
    lines = [
        f"Sentinel Report — {datetime.now().strftime('%Y-%m-%d')}",
        "=" * 40,
        f"Today's score: {score}/100",
        "",
        "Daily breakdown:",
    ]
    for category, data in (bd.get("by_category") or {}).items():
        lines.append(f"  {category}: {data} seconds")
    lines.append("")
    lines.append("Top distractions (7 days):")
    for d in top[:5]:
        lines.append(f"  {d.get('domain')}: {round((d.get('seconds') or 0) / 60, 1)} min")
    return "\n".join(lines)


def generate_report_html(conn) -> str:
    """HTML report suitable for printing/saving as PDF."""
    score = stats_mod.calculate_score(conn)
    bd = stats_mod.get_daily_breakdown(conn)
    top = stats_mod.get_top_distractions(conn, days=7)
    date = datetime.now().strftime("%Y-%m-%d")
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Sentinel Report</title><style>{_CSS}</style></head>
<body>
<h1>Sentinel Report</h1>
<p>Generated: {date}</p>
<div class="stat"><span class="stat-value">{score}</span><span class="stat-label">Score / 100</span></div>
<h2>Top Distractions (Last 7 Days)</h2>
<table><tr><th>Domain</th><th>Time</th></tr>"""
    for d in top[:10]:
        mins = round((d.get("seconds") or 0) / 60, 1)
        html += f"<tr><td>{d.get('domain')}</td><td>{mins} min</td></tr>"
    html += "</table>"
    html += "<h2>Category Breakdown</h2><table><tr><th>Category</th><th>Seconds</th></tr>"
    by_cat = bd.get("by_category") or {}
    for cat, secs in by_cat.items():
        html += f"<tr><td>{cat}</td><td>{secs}</td></tr>"
    html += "</table>"
    html += '<div class="footer">Generated by Sentinel</div></body></html>'
    return html


def generate_weekly_report(conn) -> str:
    score = stats_mod.get_week_summary(conn)
    return f"Weekly report: {score}"


def generate_monthly_report(conn) -> str:
    score = stats_mod.get_month_summary(conn)
    return f"Monthly report: {score}"


def save_report(conn, path: str, format: str = "html") -> str:
    if format == "html":
        content = generate_report_html(conn)
    else:
        content = generate_report_text(conn)
    with open(path, "w") as f:
        f.write(content)
    return path
